// Items del dom
const darkMode = document.querySelector('#dark-mode')
const background = document.getElementById('body-background')
let navItem1 = document.getElementById('nav-item1')
let navItem2 = document.getElementById('nav-item2')
let navItem3 = document.getElementById('nav-item3')
let navItem4 = document.getElementById('nav-item4')
let navItem5 = document.getElementById('nav-item5')
const sectionTitle = document.getElementById('section-title')
const enjoyText = document.getElementById('enjoy-text')
const footerText = document.getElementById('footer-text')
const check1 = document.getElementById('Cinema')
console.log(check1)

console.log(navItem1)
darkMode.addEventListener('click', toggleDarkMode)

function toggleDarkMode(){
    background.classList.toggle('bg-dark')
    navItem1.classList.toggle('text-dark')
    navItem1.classList.toggle('text-light')
    navItem2.classList.toggle('text-dark')
    navItem2.classList.toggle('text-light')
    navItem3.classList.toggle('text-dark')
    navItem3.classList.toggle('text-light')
    navItem4.classList.toggle('text-dark')
    navItem4.classList.toggle('text-light')
    navItem5.classList.toggle('text-dark')
    navItem5.classList.toggle('text-light')
    darkMode.classList.toggle('btn-dark')
    darkMode.classList.toggle('btn-light')
    sectionTitle.classList.toggle('text-light')
    enjoyText.classList.toggle('text-light')
    footerText.classList.toggle('text-light')
}
